# 整合邮件配置
spring:
  mail:
    # smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.qq.com
    # 服务协议
    protocol: smtp
    # 编码集
    default-encoding: UTF-8
    # 发送邮件的账户
    username: 2857425800@qq.com
    # 授权码
    password: uqpyqvtpoucodecg
    # 开启一些权限
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true



